### ISSUE TITLE
Setup the environment for integration testing

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/pyfulcrum#12]
We need to setup a VM to installt the pyfulcrum module and the web app. This is useful for integration testing. Please provide a list of VM requirements needed for this.

**Comment by cezio** [comment]
what we need:
 * python3 (3.5+)
 * access to postgresql+postgis
 * gdal 2.x package (with known version supported by pygdal)
 * storage for media files (for our test data we need at least 800M of storage space), i think at least 10GB for safety.

**Comment by randomorder** [comment]
we should be good
```
ssh geosolutions@dev.pyfulcrum.geo-solutions.it
```
any issues let me know

**Comment by cezio** [comment]
for the record: at the moment, pyfulcrum.lib (with cli tools) is deployed. We'll need to update deployment when webhook and api web applications are ready.
