### ISSUE TITLE
PyBackup entrypoint

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/pyfulcrum#3]
Develop a specific API to send Fulcrum's Records to the PyBackup module. An asynchronous mechanims needs to be included at this stage in order to grant high availability of the endpoint service, and reduce (throttle) downstream requests toward Fulcrum APIs which are needed to access and validate webhooks payloads.

Needed functionalities:

- [x] Module API  
~~- [ ] Asynchronous mechanism to manage the incoming records and grant high availability~~ (commented out by https://github.com/geosolutions-it/pyfulcrum/issues/3#issuecomment-431051535)

**Comment by cezio** [comment]
> ￼ Thread pool and tasks queue for asyncronous purposes (consider using Trio)

I'd strongly suggest to move this functionality to webhook web application, since it's the one that is responsible for flow control. Adding such dependency to library is a very bad practice.

**Comment by tdipisa** [comment]
deleted @cezio comment by mistake:

> Thread pool and tasks queue for asyncronous purposes (consider using Trio)

I'd strongly suggest to move this functionality to webhook web application, since it's the one that is responsible for flow control. Adding such dependency to library is a very bad practice.

**Comment by tdipisa** [comment]
@cezio 
as requirement we need to have this python module indipendent from the web application. The web application we specified in our proposal is needed only to provide a demonstration of usage of the python module (is not a real part of the required work). In addition the reason why we need to implement a thread pool in the python module is to properly manage multiple incoming requests in a context in which each request needs to be validated to be backupped: for each incoming request we need to take time to perform HTTP requests to the Fulcrum APIs for validation purposes.

**Comment by giohappy** [comment]
@cezio the goal of the project is the implementation of the backup logic. I proposed to include an asynchronous mechanism to increase the throughput of the app, but it wasn't meant to substitute upper layers' patterns (e.g. queue based request processing through Celery, or whatelse).
So, we have to focus on the logic, adopting async patterns within the core module to move all the I/O inside an event loop.
For this prupose I selected 

 - [ayncio async/awayt](https://docs.python.org/3/library/asyncio.html) native Python mechanism
 - [AIOHTTP](https://aiohttp.readthedocs.io/en/stable/) for the downstream calls toward Fulcrum APIs
 - [aiopg](https://github.com/aio-libs/aiopg) for DB access

this way, every component of the I/O path becomes asynchronous, and that's enough for us.

If there's room (=time) for improvements we may consider adopting [Queues](https://docs.python.org/3/library/asyncio-queue.html) for jobs management.

It's important that the first and prevalent goal of the project is not building a full fledged, super optimized system. Their initial reference was a simple, basic PHP script!

They will, in case, make their own web application adopting task queue/job queue based approaches, but it goes beyond the scope of this project.

**Comment by cezio** [comment]
This comment is related: https://github.com/geosolutions-it/pyfulcrum/issues/8#issuecomment-430595474

**Comment by cezio** [comment]
Few words on implementation I'm working on:

 * PyFulcrum will be using SQLAlchemy project with migrations for db storage
 * To access Api, caller will have to instantiate `ApiManager` with db session (or db connection) and api key. The latter may be optional later for some uses.
 * `ApiManager` will have properties for each resource type (`.projects`, `.forms`, etc), with uniform api (at the moment two methods: `.get(id, cached)`, `list(cached)`. This is similar to fulcrum python module, but the key difference is gateway classes for resources will handle API and db-level operations internally returning db objects. Caller will have to specify if it wants update db with live results (`cached` flag). Internally, if `cached` is set to `False`, resource gateway class will fetch data from Fulcrum API, deserialize, transform and save to db, and return db object(s). If `cached` is set to `True` (default), results are returned just from db.

 * At the moment I don't have access to live API, so I'm using data provided in documentation, and work on test cases with stub api client.

**Comment by cezio** [comment]
Module API is fairly simple, it's described in Readme: https://github.com/cezio/pyfulcrum/tree/master/lib#pyfulcrum-api
