### ISSUE TITLE
PyBackup filter/validation

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/pyfulcrum#4]
- [x] Option to possibly define a list of forms and users to be included in the backups. Records will be filtered according to this information in case it is defined.

- [x] Incoming (**filtered**) records need to be validated before starting the involved backups procedures. Payload nature and contents (as well as requests headers if possible) need to be verified before accepting the record. In case it don’t fulfill the validation rules it will be rejected.

**Comment by cezio** [comment]
> Incoming (filtered) records need to be validated before starting the involved backups procedures. Payload nature and contents (as well as requests headers if possible

Any specific criteria we should use for validation? I mean, ultimate validation is done by Fulcrum API, and assuming data come only from that source, I don't think we can do it any better than them.

**Comment by tdipisa** [comment]
@cezio 
from the proposal:

> Fulcrum Webhooks don’t implement security protocols. Caller authentication, confidentiality and data integrity are on behalf of the callee. This involves that the endpoint services must adopt security checks and implement data validation before proceeding with data processing and storage.

**Comment by cezio** [comment]
>  Webhooks don’t implement security protocols. Caller authentication, confidentiality and data integrity are on behalf of the callee. This involves that the endpoint services must adopt security checks and implement data validation before proceeding with data processing and storage.

 Ok. Authentication is one thing (it can be signature in url for example). Data validation also, but if we're using webhook to trigger fetch from API (in other words: we don't use webhook payload other way than to identify entity we need to fetch from API), then this validation would be quite simple in my understanding.

**Comment by tdipisa** [comment]
@cezio 

yes, we just need that the involved entities referred by an incoming records exist.

**Comment by tdipisa** [comment]
@cezio 
this referes something like a whitelist that can be used to filter incoming records accordingly. This functionality was designed as part of the backup infrastructure but, if we can do it just configuring the Fulcrum webhook, that should be fine too I think.

**Comment by cezio** [comment]
Validation is described in readme: https://github.com/cezio/pyfulcrum/blob/master/web/README.md#pyfulcrum-webhook-application
