### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/pyfulcrum#6]
A data model needs to be designed and implemented for PostgreSQL to store forms and records for backup purposes:

- [x] The data schema needs to be generic enough to store any Fulcrum form, field type and record information, irrespective of the form layout and structure.

- [x] The information stored within the database needs to be enough to provide users the ability to access and restore completely records data and metadata, even in case Fulcrum services are not available.

requires #1

**Comment by cezio** [comment]
for first point: https://docs.google.com/drawings/d/1fJjmCcdTUZBCJt62jeUFKFV_lNl9DQILHHOvNBm_kx8/edit?usp=drive_web&ouid=103411695112216332283

**Comment by cezio** [comment]
For clarification, in current design we don't do full data backup, only:
 * projects
 * forms
 * records with values
 * media (audio, photo, video)

Question: do we need to store anything else?

**Comment by cezio** [comment]
ok, so if record is removed we should also remove it from db, or mark it as removed?

**Comment by tdipisa** [comment]
yes, in my opinion we should consider to have an option in configuration: remove deleted objects directly or mark them as deleted without removing them. In the second case we should be able to search deleted objects through the module APIs with a specific search option/filter in order to be able to retrieve the deleted information.

**Comment by cezio** [comment]
>  the ability to access and restore completely records data and metadata, even in case Fulcrum services are not available.

Does it mean we should provide Fulcrum-compatible API?

**Comment by tdipisa** [comment]
@cezio 
no, this just means to ensure the ability to retrieve all the information connected to a backupped record (connected entities). About the APIs part, is enough in my opinion to serialize the information using the same JSON structure of the Fulcrum APIs just to help the interoperability.

**Comment by cezio** [comment]
This is implemented. Each resource object has `.payload` attribute which helds original json content for this resource, comming from Fulcrum API (except for `Value` model, which has no resource in Fulcrum API, and which value is extracted from `Record.values`). Resource-local values are stored in other model attributes.
