### ISSUE TITLE
Fulcrum PyBackup Web application

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/pyfulcrum#8]
A Web application will be implemented to:

- [x] **Be a reference example** to the usage of the Fulcrum PyBackup Python module
- [x] Public application to serve the Fulcrum Webhook endpoint service. **We can consider some task queue mechanism here but just a minimal/essential implementation. A key point is not to waste most of the time budget on this and do not invest too much on the web app (no celery, brokers, external servers, etc.)**
- [x] Public or private application to access and export backup data
- [x] **Web application for internal testing**. The web app exposes the same PyBackup module APIs through web service HTTP API.

Access to the web services can be restricted with Basic Auth or token based authentication. 

**The Python module doesn’t depend in any part on the Web application. The Python API can be used regardless of the Web application deployment**.

**notes**: 

- **The PyBackup module needs to be completely agnostinc to this web app, since the purpose of the webapp is just to provide an usage example of the PyBackup module.**

- A shared-secret key can be configured to restrict access to the endpoint HTTP service (Webhook URL).  In case it is defined, the endpoint URL activated and registered in the Fulcrum account settings must include it to grant access to the Fulcrum Webhook requests.

**Comment by cezio** [comment]
Shouldn't we split this app into webhook and web-based pyfulcrum api? I think this would be much clearer: webhook is a functionality that has real usage/client value, will be available from outside, requires specific deployment (async task queue to run data synchronization). Rest of web-based api is an example, can be hosted internally, doesn't need to be tied to webhook.

**Comment by cezio** [comment]
>  Public application to serve the Fulcrum Webhook endpoint service. We can consider some task queue mechanism here but just a minimal/essential implementation. A key point is not to waste most of the time budget on this and do not invest too much on the web app (no celery, brokers, external servers, etc.)

This is a bit self-contradicting statement. Implementing task queue from scratch won't be faster than using ready task queue software. Celery has quite good integration with Flask, so I don't see why we shouldn't use it.

**Comment by cezio** [comment]
> Public application to serve the Fulcrum Webhook endpoint service. We can consider some task queue mechanism here but just a minimal/essential implementation. A key point is not to waste most of the time budget on this and do not invest too much on the web app (no celery, brokers, external servers, etc.)

task queue may be helpful in future, but now it looks like webhook processing is fairly quick (1-2 seconds top from receiving webhook to saving payload to db). Do we need task queue at this point?
